### ISSUE TITLE
command line option ‘-Wimplicit-int’ is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by ElAnonimo** [rubyjs/mini_racer#123]
Happens on Xubuntu 16. Is there a workaround to solve the issue?

```
make "DESTDIR="
compiling mini_racer_extension.cc
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
```

**Comment by ignisf** [comment]
We probably could update the compiler options to not generate warnings. (Just checking... You see that these are warnings and should have no effect on the installation, right?)

**Comment by ElAnonimo** [comment]
The options listed in the output prevented the `mini_racer` gem from installation.

**Comment by ignisf** [comment]
Could you paste the complete output? How can warnings prevent the installation?

**Comment by ElAnonimo** [comment]
The installation options did.
current directory:
/home/*/.rvm/gems/ruby-2.5.1/gems/mini_racer-0.2.4/ext/mini_racer_extension
make "DESTDIR="
compiling mini_racer_extension.cc
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
cc1plus: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1plus: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1plus: warning: unrecognized command line option ‘-Wno-tautological-compare’
linking shared-object mini_racer_extension.so
mini_racer_extension.so: final close failed: Invalid operation
collect2: error: ld returned 1 exit status
Makefile:257: recipe for target 'mini_racer_extension.so' failed
make: *** [mini_racer_extension.so] Error 1

make failed, exit code 2

**Comment by ignisf** [comment]
For some reason the so fails to link. It's not due to the warnings. Could you paste the output of `gem env` and `gem list | grep libv8`?

**Comment by ElAnonimo** [comment]
`gem env` returned
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/rosewell/.rvm/gems/ruby-2.5.1@2.5.1
  - USER INSTALLATION DIRECTORY: /home/rosewell/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/share/rvm/rubies/ruby-2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/rosewell/.rvm/gems/ruby-2.5.1@2.5.1/bin
  - SPEC CACHE DIRECTORY: /home/rosewell/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/rosewell/.rvm/gems/ruby-2.5.1@2.5.1
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/rosewell/.rvm/gems/ruby-2.5.1@2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /usr/share/rvm/rubies/ruby-2.5.1/bin
     - /usr/share/rvm/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1/bin
     - /home/rosewell/.rvm/gems/ruby-2.5.1@global/bin
     - /home/rosewell/.nvm/versions/node/v10.10.0/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0@global/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0/bin
     - /home/rosewell/.rvm/gems/ruby-2.3.0@global/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /snap/bin
```

`sudo gem list | grep libv8` returned `libv8 (6.7.288.46.1 x86_64-linux)`.

**Comment by ignisf** [comment]
Hmmm... 

Could you try upgrading your compiler toolchain?

Similar issues: https://github.com/google/cadvisor/issues/2100, https://github.com/vmg/redcarpet/issues/619

**Comment by ElAnonimo** [comment]
All the installations were fresh so they were supposed to be the latest. I'll into the issues above.

Earlier there were warnings about installing only the Ruby dependencies and not the Linux ones. The installer suggested a command to install for Linux too which I ran.
The Gemfile containes `gem 'mini_racer', platforms: :ruby`.

**Comment by tisba** [comment]
Hey everyone! This issue looks a bit stale :) Ruby 2.5 is no longer supported by mini_racer for example 😉 

Do you still have this issue with recent mini_racer and supported Ruby versions, @ElAnonimo?

**Comment by ElAnonimo** [comment]
Probably no since I quitted using it.

**Comment by nightpool** [comment]
This warning still exists for me on 2.6

**Comment by chrishough** [comment]
I am getting a similar issue https://github.com/rubyjs/mini_racer/issues/234 here.
