### ISSUE TITLE
check failed: last_checksum == des_checksum in test_snapshots_can_be_warmed_up_with_no_side_effects

### ISSUE THREAD

**Issue by ignisf** [rubyjs/mini_racer#154]
When running the test suite against mini_racer linked with libv8 7.8.279.23 I get the following error:

```
#
# Fatal error in ../../src/heap/read-only-heap.cc, line 58
# Check failed: last_checksum == des_checksum (<unprintable> vs. <unprintable>).
#
#
#
#FailureMessage Object: 0x7ffc58734750
```

Full log here:
https://gist.githubusercontent.com/ignisf/8736504081f6f1f9c5d75de3dff004dd/raw/6d4b3397f6128e9b6d664a29b7bcd33c90603341/gistfile1.txt

**Comment by SamSaffron** [comment]
Aha, this feels related to snapshot stuff, if we comment out snapshot tests
does everything else work?

**Comment by tisba** [comment]
A long time has passed - is this issue still valid?
