### ISSUE TITLE
Load error with 0.3.0 and 0.3.1

### ISSUE THREAD

**Issue by esb** [rubyjs/mini_racer#169]
The new versions are causing a crash on my development system when I load them. It's a Centos 7 system with libv8 (8.4.255.0 x86_64-linux) installed.

This is the message

```
/usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so (LoadError)
```

Rolling back to 0.2.15 solves the problem.

**Comment by SamSaffron** [comment]
@nightpool any ideas here? 

@esb can you repro this in a docker container?

**Comment by nightpool** [comment]
It looks like an ABI problem, which is strange, since bundler should have compiled the gem with the exact same libraries Ruby is using when you installed it. Did you happen to compile the gems on a different system then you're running them on? I guess the other possibility is that you're seeing this error using libv8 on a GCC 4.8 system, which seems less likely, because I thought libv8 compiled everything in statically, but possible.

**Comment by esb** [comment]
The gem was compiled on the same system as the reported error.

This is on Centos 7, which has GCC 4.8.5 as standard.

**Comment by nightpool** [comment]
You may want to try compiling libv8 from source, my guess is that there is
some ABI incompatibility between the version of libstdc++ v8 was compiled
with and the one on your system. unfortunately, I'm not able to find
anything about the issue by googling.

**Comment by esb** [comment]
Ok, I installed devtools-9 and installed mini_racer using the gcc 9 complier under the scl shell.

That seems to have resolved the issue.

**Comment by SamSaffron** [comment]
@nightpool I wonder if we should start pushing binary versions of mini racer, at least for linux?

**Comment by valscion** [comment]
I've also got the same issue, but in production-like environments. They're also running CentOS 7 and have installed libv8 gem from the pre-compiled binary version.

I can help reproduce this in a few weeks, as today's my last day before vacation so unfortunately can't help do that right now.

This is what's output when the gem gets required by `bundle exec rake db:migrate`:

```
LoadError: /var/app/vendor/bundle/ruby/2.6.0/gems/mini_racer-0.3.0/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /var/app/vendor/bundle/ruby/2.6.0/gems/mini_racer-0.3.0/lib/mini_racer_extension.so
```

**Comment by ccasabona** [comment]
I have the same problem on Centos 7 (with gcc 4.8.5) as valscion.  Taking a cue from [ussue 50](https://github.com/rubyjs/mini_racer/issues/50), I tried installing newer versions of gcc.  Versions 7.4 and 8.4 give the same error message.  

I have a Centos 8 staging environment with gcc 8.1 installed, and this works fine.

**Comment by kingdonb** [comment]
I also have this issue on an Amazon Linux system which is similar to CentOS.

I seem to be on this GCC version:
```
gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
```

**Comment by SamSaffron** [comment]
I want to get this sorted, but think the only easy thing to do here will be to compile mini_racer to a binary and publish that for Linux x64 to match the v8 binary release.

PR totally welcome to make the packaging changes so we publish a "source" release + a binary release for x64 linux

**Comment by Overload119** [comment]
I also have this issue.

> Ok, I installed devtools-9 and installed mini_racer using the gcc 9 complier under the scl shell.
> That seems to have resolved the issue.

@esb can you share what you did in more detail to unblock yourself?

**Comment by nightpool** [comment]
@SamSaffron I don't know enough about C build chains to know if that will
fix it, but if you can reproduce the issue locally it sounds like it's
worth a shot

**Comment by Overload119** [comment]
Okay, here how I unblocked using @esb's tips.

sudo yum group install "Development Tools"
sudo yum install centos-release-scl # handles multiple versions of scl
scl enable devtoolset-9 bash # set everything up for version 9 
gcc --version # this should be 9 now
source scl_source enable devtoolset- 9 # add to bash so you always use this version when deploying

Clear out your bundle and re-run bundle. It seems to work now!

**Comment by ccasabona** [comment]
This still does not work on my Centos 7 system.  The gems compile correctly, but, under passenger, the app will not start.

/var/www/html/*******.com/public/shared/bundle/ruby/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /var/www/html/*******.com/public/shared/bundle/ruby/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so (LoadError)
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)

**Comment by andresbarcenas** [comment]
Any update on this? I am experiencing the same issue on CentOS 7:

LoadError: /home/deployer/apps/fore/shared/bundle/ruby/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /home/deployer/apps/fore/shared/bundle/ruby/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.so
/home/deployer/apps/fore/shared/bundle/ruby/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:2:in `require'
/home/deployer/apps/fore/shared/bundle/ruby/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.6.2/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'

CentOS Linux release 7.9.2009 (Core)
gcc-4.8.5-44.el7.x86_64
ruby '2.6.2'

**Comment by valscion** [comment]
I think https://github.com/rubyjs/mini_racer/issues/169#issuecomment-664747562 by @SamSaffron in this thread is still relevant:

> PR totally welcome to make the packaging changes so we publish a "source" release + a binary release for x64 linux

**Comment by ccasabona** [comment]
OK.  How would one go about doing that?

**Comment by salzig** [comment]
this can be easily reproduced using docker with ruby 2.4.1
```
$ docker run -it ruby:2.4.1 bash
# now within the ruby:2.4.1 based container:
$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
$ gem install mini_racer
$ ruby -e 'require "mini_racer"'
```
results in
```
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/bundle/gems/mini_racer-0.3.1/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /usr/local/bundle/gems/mini_racer-0.3.1/lib/mini_racer_extension.so (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/mini_racer-0.3.1/lib/mini_racer.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from -e:1:in `<main>'
```

**Comment by SamSaffron** [comment]
Sadly old GCC is simply unsupportable, we need quite recent CXX feature to link to v8 and consume it properly
