### ISSUE TITLE
can't execute rails commands after upgrading to the last version

### ISSUE THREAD

**Issue by fccoelho7** [rubyjs/mini_racer#174]
I've needed to update the gem to the last version, to run a rails app on my MAC, after upgrading to the version 0.3.1, I'm getting an error on the `circleci/ruby:2.4.1-jessie-node` docker image.

```sh
# gemfile.lock
    mini_racer (0.3.1)
      libv8 (~> 8.4.255)
```

I'm getting this message:

```sh
bin/rails db:schema:load --trace
rails aborted!
LoadError: /home/circleci/project/vendor/bundle/gems/mini_racer-0.3.1/lib/mini_racer_extension.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE - /home/circleci/project/vendor/bundle/gems/mini_racer-0.3.1/lib/mini_racer_extension.so
/home/circleci/project/vendor/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/home/circleci/project/vendor/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/circleci/project/vendor/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/circleci/project/vendor/bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/home/circleci/project/vendor/bundle/gems/mini_racer-0.3.1/lib/mini_racer.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/home/circleci/project/config/application.rb:7:in `<top (required)>'
/home/circleci/project/Rakefile:4:in `require_relative'
/home/circleci/project/Rakefile:4:in `<top (required)>'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/home/circleci/project/vendor/bundle/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/circleci/project/vendor/bundle/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/circleci/project/vendor/bundle/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/circleci/project/vendor/bundle/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Exited with code exit status 1
CircleCI received exit code 1
```

this same error shows up if I run another command, like `rspec`

any idea?

**Comment by SamSaffron** [comment]
Is this gcc related cc @nightpool  ? something about very old GCCs not being able to compile stuff right?

**Comment by nightpool** [comment]
that sounds right—we need a modern version of libc++ installed on the machine, should be compatible with at least gcc 5.4

**Comment by ikinye** [comment]
Hi. all
I updated ruby version from 2.3.3 to 2.4.10 and mini_racer to 0.3.1.
And then got same problem that described in above. 

After reading some article, I updated gcc version to 9 from 4.x. then run "bundle update".
But same situation. 

Is there any another suggestion?

Here is the environment ---

`RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.8
  - RUBY VERSION: 2.4.10 (2020-03-31 patchlevel 364) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/ubuntu/.rvm/gems/ruby-2.4.10
  - USER INSTALLATION DIRECTORY: /home/ubuntu/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/ubuntu/.rvm/rubies/ruby-2.4.10/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/ubuntu/.rvm/gems/ruby-2.4.10/bin
  - SPEC CACHE DIRECTORY: /home/ubuntu/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux`
---
`gcc (Ubuntu 9.3.0-11ubuntu0~14.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.`

mini_racer version is 0.3.1

**Comment by nightpool** [comment]
@ikinye you may have to blow away the installed gems—gcc isn't part of bundler so just running bundle update won't do anything

**Comment by ikinye** [comment]
@nightpool Thanks for comment. I will remove the ruby and whole gemset and try again.

**Comment by ikinye** [comment]
This worked for me. 

Update gcc version to 9 or higher
`CC={gcc path} rvm install {ruby version} --enable-shared`

Note that we should remove gem(include directory) after this command then re-install.

**Comment by tisba** [comment]
looks like this is related to https://github.com/rubyjs/mini_racer/issues/203

**Comment by tisba** [comment]
I'm going to close this issue. The initial report is using a very old version of mini_racer and an even older version of Ruby 2.4 (mini_racer supports Ruby >=2.6) which is no longer supported by mini_racer.

Let us know if the issue still persists for you @fccoelho7.
