### ISSUE TITLE
MiniRacer can't load Handlebars.js

### ISSUE THREAD

**Issue by creature** [rubyjs/mini_racer#183]
I'm pretty certain this is not an issue with MiniRacer, but I'd appreciate any pointers to the source of the problem and how to fix it. 

[Handlebars](https://github.com/handlebars-lang/handlebars.js/) is a popular JavaScript templating library that I'm using in one of my Ruby projects. There are [Ruby bindings](https://github.com/cowboyd/handlebars.rb), but they [rely on therubyracer](https://github.com/cowboyd/handlebars.rb/blob/77bd6a4699a4d297c8d6fa93a280f3ca21d2a137/handlebars.gemspec#L15) so are tied to an old libv8. Therubyracer can [load Handlebars fine](https://github.com/cowboyd/handlebars.rb/blob/77bd6a4699a4d297c8d6fa93a280f3ca21d2a137/lib/handlebars/context.rb#L7-L9): 

```ruby
# Gemfile
source "https://rubygems.org"
gem "handlebars-source"
gem "therubyracer"
```

```
# Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    handlebars-source (4.7.6)
    libv8 (3.16.14.19)
    ref (2.0.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref

PLATFORMS
  ruby

DEPENDENCIES
  handlebars-source
  therubyracer

BUNDLED WITH
   2.1.4
```

```ruby
# demo.rb
require 'handlebars/source'
require 'v8'

js = V8::Context.new
js.load(Handlebars::Source.bundled_path)
js.eval('Handlebars')
puts "Handlebars was loaded successfully." 
```
------ 
I think this should be a MiniRacer equivalent, but I get a circular reference error when I run this: 

```ruby
# Gemfile
source "https://rubygems.org"
gem 'handlebars-source'
gem 'mini_racer'
```

```
# Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    handlebars-source (4.7.6)
    libv8 (8.4.255.0-x86_64-darwin-18)
    mini_racer (0.3.1)
      libv8 (~> 8.4.255)

PLATFORMS
  ruby

DEPENDENCIES
  handlebars-source
  mini_racer

BUNDLED WITH
   2.1.4
```

```ruby
# demo.rb
require 'handlebars/source'
require 'mini_racer'
js = MiniRacer::Context.new
js.load(Handlebars::Source.bundled_path)
js.eval('Handlebars')
puts "Handlebars was loaded successfully."
```

```
bundle exec ruby demo.rb
Traceback (most recent call last):
	9: from demo.rb:5:in `<main>'
	8: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:206:in `eval'
	7: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:206:in `synchronize'
	6: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:208:in `block in eval'
	5: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:329:in `timeout'
	4: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:209:in `block (2 levels) in eval'
	3: from /Users/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_racer-0.3.1/lib/mini_racer.rb:209:in `eval_unsafe'
	2: from JavaScript at JSON.stringify (<anonymous>)
	1: from JavaScript --- property 'default' closes the circle
JavaScript --> starting at object with constructor 'HandlebarsEnvironment': TypeError: Converting circular structure to JSON (MiniRacer::RuntimeError)
```

I also have a similar demo for ExecJS, which a) seems to use Node as a runtime on my system and b) also fails to import Handlebars. I can share that example if it's useful. 

Looking at [the JavaScript source](https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.js), it looks like this has used Webpack to generate a "universal bundle". I [found](https://github.com/jantimon/html-webpack-plugin/issues/870) [some](https://github.com/webpack/webpack/issues/1788) [reports](https://github.com/webpack/webpack/issues/2759) of similar issues, but I don't understand the underlying cause or how I should fix this. My best guess is it's [related to exporting a `default` property](https://github.com/webpack/webpack/issues/1788), but I don't know why this would fail on newer V8 runtimes. Any pointers would be appreciated!

**Comment by SamSaffron** [comment]
My guess here is that we are trying to export an object with a loop: 

Pretty easy to repro with: 

`MiniRacer::Context.new.eval("var a = {}; var b = {a: a}; a['b'] = b; b")`

MiniRacer, by design, can not deal efficiently with loops like this. 

I recommend taking a step back here... why eval all of handlebars. All you need is a function that takes input that is a string and then returns a string.

**Comment by creature** [comment]
> I recommend taking a step back here... why eval all of handlebars. All you need is a function that takes input that is a string and then returns a string.

I thought about this some more, along with the Node example above, and I think I have a better understanding of what's happening now. Here's my explanation of the problem – hopefully someone can let me know if I've got it right. :) 

1. When we run `js.eval('Handlebars')`, the JS runtime evaluates `Handlebars` without problems. It evaluates to an object. 
2. To pass that object back to Ruby, V8 needs to serialise it. That invokes `JSON.stringify` – and that can't cope with circular references.
3. If we access some sub-part of Handlebars instead, though, we won't get an error. To tweak the MiniRacer example above: 
    ```ruby 
    require 'handlebars/source'
    require 'mini_racer'
    js = MiniRacer::Context.new
    js.load(Handlebars::Source.bundled_path)
    result = js.eval('Handlebars.compile("Hello #{name}")')
    puts "Handlebars was loaded successfully."
    puts result.inspect
   ```
   This returns a `MiniRacer::JavaScriptFunction`. 

I don't believe [we can invoke JS functions directly in MiniRacer](https://github.com/rubyjs/mini_racer/issues/59), which I guess is kind of the nub of the issue: the Ruby bindings are essentially proxying through to the JavaScript functions directly, but I think for MiniRacer I'd have to take a slightly different approach.

**Comment by SamSaffron** [comment]
Yes that is basically it, MiniRacer does not proxy objects, back when therubyracer was doing it we had so many weird and wonderful issues keeping track of object lifetimes. MiniRacer pulled away from that pattern and tries to place a very heavy wall between runtimes to avoid these issues.

The best idea for handlebars is just to directly eval things it needs vs attempting object proxies. You can still pre-compile stuff if needed, just keep it in the Context, then fish out the compiled handlebars with a single eval call.

**Comment by creature** [comment]
Thanks again for the help! I'm still investigating solutions to my underlying problem, but I think this issue is closable now.

**Comment by gi** [comment]
@creature I wrote a Ruby API for Handlebars.js using MiniRacer: https://github.com/gi/handlebars-ruby. 

Check it out. I would love some feedback.

**Comment by creature** [comment]
Interesting, thanks for letting me know! I'll try to find time to look at that, and [minibars](https://github.com/combinaut/minibars) too.

(For my use case, I wrote a NodeJS helper tool that renders files and used [`IO.popen`](https://ruby-doc.org/core-2.7.3/IO.html#popen-method) to issue it commands.)
