### ISSUE TITLE
Embeding ruby objects

### ISSUE THREAD

**Issue by majkelcc** [rubyjs/mini_racer#194]
Hello 👋

`Therubyracer` gem allowed embedding ruby objects like this:

```
cxt['foo'] = "bar"
cxt.eval('foo') # => "bar"
```

Is there an equivalent in `mini_racer`?

I'm looking for a way to properly assign a multiline ruby string to a javascript var in MiniRacer's context.

**Comment by SamSaffron** [comment]
generally you would handle the interoperability yourself. Inspect and json helpers take care of safe interop. 

```
irb(main):001:0> require 'mini_racer'
=> true
irb(main):002:0> ctx = MiniRacer::Context.new
=> #<MiniRacer::Context:0x0000563c7c557ee0 @functions={}, @timeout=nil, @max_memory=nil, @current_exception=nil, @isolate=...
irb(main):003:0> 
irb(main):004:0> ctx.eval("a = #{"some multi\n line \t with tabs".inspect}")
=> "some multi\n line \t with tabs"
irb(main):005:0> ctx.eval("a")
=> "some multi\n line \t with tabs"
```

**Comment by majkelcc** [comment]
@SamSaffron thank you so much! I didn't know that `inspect` can be used for this. Closing 🙂
