### ISSUE TITLE
Can't install on Heroku

### ISSUE THREAD

**Issue by brandoncc** [rubyjs/mini_racer#209]
I upgraded from 0.2.9 and my dyno won't build on Heroku. It claims to install, but then says that libv8 is missing:

```
Fetching mini_racer 0.4.0
Installing mini_racer 0.4.0 with native extensions
...
/tmp/build_1bf26611/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find libv8-node-15.14.0.1 in any of the sources (Bundler::GemNotFound) 
```

I have added gcc-8 to my Aptfile:

```
       The following additional packages will be installed:
         cpp-8 libasan5 libgcc-8-dev libubsan1
       Suggested packages:
         gcc-8-locales gcc-8-multilib gcc-8-doc libgcc1-dbg libgomp1-dbg libitm1-dbg
         libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg
         libmpx2-dbg libquadmath0-dbg
       The following NEW packages will be installed:
         cpp-8 gcc-8 libasan5 libgcc-8-dev libubsan1
```

Any help would be appreciated!

**Comment by jonatasrancan** [comment]
Having the same problem, after updating to `0.4.0` and trying to deploy to heroku

```
...
Installing libv8-node 15.14.0.1 (x86_64-linux-musl)
Fetching mini_racer 0.4.0
Installing mini_racer 0.4.0 with native extensions
...
Bundle complete! 135 Gemfile dependencies, 240 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Removing ffi (1.13.1)
       Removing libv8-7.3.492.27.1-x86_64 (linux)
       Removing mini_racer (0.2.5)
       Removing ethon (0.12.0)
       Bundle completed (26.73s)
       Cleaning up the bundler cache.
       Could not find libv8-node-15.14.0.1 in any of the sources
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     /tmp/build_d0bd5a40/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find libv8-node-15.14.0.1 in any of the sources (Bundler::GemNotFound)
```

**Comment by nightpool** [comment]
I ran into this issue with Bundler 1, the fix I found was complicated. You have to bundle locally with `BUNDLE_SPECIFIC_PLATFORMS=true` and the `x86_64-linux` platform enabled. Then you have to use this patchset for your next deploy: https://github.com/Genius/heroku-buildpack-ruby/commit/50ac7aa7510867362ce793174d62b65dace6ab1f

This is because setting BUNDLE_SPECIFIC_PLATFORMS on heroku using config:set will break your currently running application. Setting it in this way will set the right variable at build time, instead of setting it for both the currently running build and the next (working) build.

**Comment by jonatasrancan** [comment]
@nightpool thanks, in the end, we updated our bundler, and it worked. For us no need to use that buildpack.

**Comment by brandoncc** [comment]
Thank you both for the input! I will look into how to upgrade bundler. I remember Heroku used to have a ton of problems with Bundler 2, but I assume those must be resolved now.

**Comment by nightpool** [comment]
@brandoncc https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issues has a list of known issues

**Comment by brandoncc** [comment]
Sweet, thank you @nightpool!
