### ISSUE TITLE
Fails to build ruby:3.1-rc-buster

### ISSUE THREAD

**Issue by tobymao** [rubyjs/mini_racer#219]
```
FROM ruby:3.1-rc-buster

RUN gem install mini_racer
```

Successfully installed libv8-node-15.14.0.1-x86_64-linux
Building native extensions. This could take a while...
ERROR:  Error installing mini_racer:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/mini_racer-0.4.0/ext/mini_racer_extension
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20211111-7-9p3g4c.rb extconf.rb
checking for -lpthread... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-pthread-dir
        --without-pthread-dir
        --with-pthread-include
        --without-pthread-include=${pthread-dir}/include
        --with-pthread-lib
        --without-pthread-lib=${pthread-dir}/lib
        --with-pthreadlib
        --without-pthreadlib
        --enable-debug
        --disable-debug
        --enable-asan
        --disable-asan
/usr/local/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Libv8::Node::Location::Vendor (Psych::DisallowedClass)
        from /usr/local/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /usr/local/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
        from /usr/local/lib/ruby/3.1.0/psych.rb:370:in `load'
        from /usr/local/bundle/gems/libv8-node-15.14.0.1-x86_64-linux/ext/libv8-node/location.rb:21:in `block in load!'
        from /usr/local/bundle/gems/libv8-node-15.14.0.1-x86_64-linux/ext/libv8-node/location.rb:20:in `open'
        from /usr/local/bundle/gems/libv8-node-15.14.0.1-x86_64-linux/ext/libv8-node/location.rb:20:in `load!'
        from /usr/local/bundle/gems/libv8-node-15.14.0.1-x86_64-linux/lib/libv8/node.rb:8:in `configure_makefile'
        from extconf.rb:64:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/3.1.0/mini_racer-0.4.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/mini_racer-0.4.0 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/3.1.0/mini_racer-0.4.0/gem_make.out
The command '/bin/sh -c gem install mini_racer' returned a non-zero code: 1
[

**Comment by SamSaffron** [comment]
working with our pre release, going to just go ahead and release it.

**Comment by tobymao** [comment]
thanks, works now

**Comment by mjamalq** [comment]
What's the solution, please? I'm getting the same error.

**Comment by tobymao** [comment]
upgrade to 0.5

**Comment by mjamalq** [comment]
Nah, I'm at Ruby 2.5. If I upgrade to the 0.5 version, that would ask for at least the 2.6 version for Ruby.
