### ISSUE TITLE
Bundler can't install 0.6.2

### ISSUE THREAD

**Issue by gabldotink** [rubyjs/mini_racer#236]
**I don't know if this is the right place to ask; feel free to remove this or redirect me if not.**

I need to install mini_racer (0.6.2) for a project, but it displays an error when I try to use `bundle install` (no other gems seem to have problems). Log:

```current directory:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
/home/[username]/.rvm/rubies/ruby-2.7.5/bin/ruby -I
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0 -r
./siteconf20220209-58365-19f34ip.rb extconf.rb
checking for -lpthread... yes
creating Makefile

current directory:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR=" clean

current directory:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR="
compiling mini_racer_extension.cc
In file included from
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8.h:30,
                 from mini_racer_extension.cc:6:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8-internal.h:
In function ‘VALUE convert_v8_to_ruby(v8::Isolate*, v8::Local<v8::Context>,
v8::Local<v8::Value>)’:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8-internal.h:364:48:
warning: ‘stackCounter.StackCounter::isolate’ may be used uninitialized in this
function [-Wmaybe-uninitialized]
  364 |     return *reinterpret_cast<void* const*>(addr);
      |                                                ^
mini_racer_extension.cc:573:18: note: ‘stackCounter.StackCounter::isolate’ was
declared here
  573 |     StackCounter stackCounter(isolate);
      |                  ^~~~~~~~~~~~
linking shared-object mini_racer_extension.so
/usr/bin/ld: cannot find
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/x86_64-linux/libv8/obj/libv8_monolith.a:
No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:262: mini_racer_extension.so] Error 1

make failed, exit code 2

Gem files will remain installed in
/home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2 for inspection.
Results logged to
/home/[username]/.rvm/gems/ruby-2.7.5/extensions/x86_64-linux/2.7.0/mini_racer-0.6.2/gem_make.out

/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in
`run'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:51:in
`block in make'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in
`each'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in
`make'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in
`block in build'
  /home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/tempfile.rb:291:in `open'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in
`build'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in
`block in build_extension'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in
`synchronize'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in
`build_extension'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in
`block in build_extensions'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in
`each'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in
`build_extensions'
/home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/installer.rb:844:in
`build_extensions'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/source/rubygems.rb:204:in
`install'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:54:in
`install'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/worker.rb:62:in
`apply_func'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/worker.rb:57:in
`block in process_queue'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in
`loop'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in
`process_queue'
/home/[username]/.rvm/gems/ruby-2.7.5/gems/bundler-2.3.7/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing mini_racer (0.6.2), and Bundler
cannot continue.

In Gemfile:
  mini_racer
```

I've tried removing mini_racer from the Gemfile.lock, but I still need it for one of the steps during compilation.

System version: Ubuntu 21.10
Bundler: 2.3.7
Ruby: 2.7.5
(I'm using Ruby 2.7.5 as recommended on the repo I'm trying to compile.)
Tell me if you need any more version numbers.

Thank you for any and all help.

**Comment by tisba** [comment]
Please make sure to have platforms specified in `Gemfile.lock`, via `bundle lock --add-platform x86_64-linux` (or what `ruby -v` reports). There is a pending issue in Rubygems resulting in picking up the wrong platform, `x86_64-linux-musl` in your case.

**Comment by gabldotink** [comment]
I can't reopen this issue, but `bundle install` is still not working, even after adding the correct platform (I also tried removing the incorrect one; didn't work then either). Thanks for your help.

**Comment by Ecco** [comment]
For what it's worth, I'm also running into the same issue trying to install `mini_racer` on Debian 11 (so a glibc-based x86_64 system). Of course this is not directly related to `mini_racer` itself but to the `libv8-node` gem.

Thanks to @tisba in #231 I got it to work manually (i.e. via `gem install`) but I haven't found a way that works through `bundle install` yet.

Here are my findings:
||Does **not** work (musl variant)|Works (plain glibc variant)|
|-|-|-|
|gem|`gem install libv8-node`<br>`gem install --platform x86_64-linux libv8-node` |`gem install libv8-node --version 16.10.0.0 --platform x86_64-linux-libc` |
|bundler|`bundle lock --add-platform x86_64-linux`<br>`bundle lock --add-platform x86_64-linux-libc`| I haven't found an option that works!|

**Comment by Ecco** [comment]
I did try a bunch of different `Gemfile.lock` option, and none of them would install the non-musl variant.
Here's an example of a Gemfile.lock that does not work (even though I really think it should):
```
GEM
  remote: https://rubygems.org/
  specs:
    libv8-node (16.10.0.0-x86_64-linux)
    mini_racer (0.6.2)
      libv8-node (~> 16.10.0.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  mini_racer

BUNDLED WITH
   2.1.4
```

**Comment by tisba** [comment]
Bundler 2.1.4 is too old, try `gem update - -system`

**Comment by Ecco** [comment]
Oh, ok! I also *did* find a workaround with Bundler 2.1.4: `BUNDLE_SPECIFIC_PLATFORM=1 bundle install` will do the trick

**Comment by Ecco** [comment]
So bundler 2.3.7 (that I got from `gem update --system`) does indeed work out of the box! Thanks so much for your help @tisba !

**Comment by gabldotink** [comment]
OUTPUTS: The logs are the same, except for line 4.
original: `./siteconf20220209-58365-19f34ip.rb extconf.rb`
now: `./siteconf20220211-134517-12op0h8.rb extconf.rb`

<details>
  <summary>relevant parts of Gemfile and Gemfile.lock (couldn't get codeblocks working)</summary>
  - GEMFILE -
  1 source 'https://rubygems.org'
  2 ruby "~> 2.7"

  109 group :test, :production do
  110 gem 'pg', '\~> 1.2'
  111 gem "mini_racer", "\~> 0.6.2"
  112 end

  \- GEMFILE.LOCK -
 1428 mini_racer (0.6.2) [[gem listing]]

 1646 PLATFORMS
 1647   ruby
 1648   x86_64-linux

 1719 RUBY VERSION
 1720  ruby 2.7.2p137
 1720
 1721   BUNDLED WITH
 1723   2.3.7
</details>

Using `gem install mini_racer --version 0.6.2 --platform x86_64-linux` gives a different, but still unsuccessful error:

<details>
  <summary>error</summary>
Building native extensions. This could take a while...
ERROR:  Error installing mini_racer:
	ERROR: Failed to build gem native extension.

    current directory: /home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
/home/[username]/.rvm/rubies/ruby-2.7.5/bin/ruby -I /home/[username]/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0 -r ./siteconf20220211-140391-vhibs6.rb extconf.rb
checking for -lpthread... yes
creating Makefile

current directory: /home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR=" clean

current directory: /home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR="
compiling mini_racer_extension.cc
In file included from /home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8.h:30,
                 from mini_racer_extension.cc:6:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8-internal.h: In function ‘VALUE convert_v8_to_ruby(v8::Isolate*, v8::Local<v8::Context>, v8::Local<v8::Value>)’:
/home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include/v8-internal.h:364:48: warning: ‘stackCounter.StackCounter::isolate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  364 |     return *reinterpret_cast<void* const*>(addr);
      |                                                ^
mini_racer_extension.cc:573:18: note: ‘stackCounter.StackCounter::isolate’ was declared here
  573 |     StackCounter stackCounter(isolate);
      |                  ^~~~~~~~~~~~
linking shared-object mini_racer_extension.so
/usr/bin/ld: cannot find /home/[username]/.rvm/gems/ruby-2.7.5/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/x86_64-linux/libv8/obj/libv8_monolith.a: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:262: mini_racer_extension.so] Error 1

make failed, exit code 2

Gem files will remain installed in /home/[username]/.rvm/gems/ruby-2.7.5/gems/mini_racer-0.6.2 for inspection.
Results logged to /home/[username]/.rvm/gems/ruby-2.7.5/extensions/x86_64-linux/2.7.0/mini_racer-0.6.2/gem_make.out
</details>

`gem install mini_racer --version 0.6.2 --platform x86_64-linux` outputs:

```
*** LOCAL GEMS ***

libv8-node (16.10.0.0 x86_64-linux x86_64-linux-musl)

*** LOCAL GEMS ***
```
So libv8 is installed. I tried uninstalling libv8 and trying again, but it still failed.

Thanks for your patience. I'm still pretty new to Linux, as you may be able to tell.

**Comment by gabldotink** [comment]
Quick update: I was able to get mini_racer 0.6.2 to install by changing the Gemfile's line:
`gem "mini_racer", "~> 0.6.2"` to `gem 'mini_racer', :git => 'git://github.com/rubyjs/mini_racer.git'`.
I don't know if this issue is quite ready to be closed, but I wanted to give an update. Thank you for your help.

**Comment by tisba** [comment]
Hey @gabldotink. You should not have to switch to git (actually I don't really know why this would help). Are you sure you've removed **all** `libv8-node` versions? (`gem uninstall --all mini_racer libv8-node`). The error message still looks like, an incorrect `libv8-node` gets picked up.

See also https://github.com/rubyjs/mini_racer#troubleshooting

**Comment by gabldotink** [comment]
OK, I switched back to the original declaration, removed `libv8-node`, and then `bundle install` worked. It's possible I didn't install `mini_racer` correctly after specifying the git source, and that I just misunderstood.

Thank you for your help.

**Comment by Nowaker** [comment]
It still doesn't work for me. I've followed all the guidance from this ticket.

1. Latest bundler. `Bundler version 2.3.8`
2. `gem uninstall --all mini_racer libv8-node`

Still: `Installing libv8-node 16.10.0.0 (x86_64-linux-musl)` for both `bundle install` and `BUNDLE_SPECIFIC_PLATFORM=1 bundle install`.

This is not musl. This is glibc.

```
$ ldd /bin/ls
	linux-vdso.so.1 (0x00007ffdecbbb000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fd072793000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007fd07258e000)
	libacl.so.1 => /lib64/libacl.so.1 (0x00007fd072385000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd071fda000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fd071d76000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd071b72000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd0729ba000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007fd07196d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd07174f000)
```

Help?

**Comment by tisba** [comment]
hey @Nowaker. have you checked all items in https://github.com/rubyjs/mini_racer/#troubleshooting? Have you set your platform correctly? If that's the case, please tell us what Ruby version you're using and paste a (minimal) `Gemfile.lock`.

**Comment by ohiodn8** [comment]
Had a similar issue with `ruby 2.7.6` and `rails 5.2.8.1`. Following these steps from @tisba  and @gabldotink  fixed the issue: 
```
gem update --system
gem uninstall --all mini_racer libv8-node
bundle install
```

Note: this was an attempt to upgrade an existing rails app from ruby 2.7.4 and rails 5.2.6 to the version specified above. I removed the Gemfile.lock from the app directory before running the commands above (but it shouldn't matter). I was able to install `mini_racer (0.6.3)`

**Comment by Nowaker** [comment]
> I removed the Gemfile.lock from the app directory before running the commands above (but it shouldn't matter). 

Of course it matters as removing Gemfile.lock changes how the dependencies are resolved.

This is a very random way of working around this problem, and I wouldn't recommend anyone to do it this way.

**Comment by rellampec** [comment]
> Please make sure to have platforms specified in `Gemfile.lock`, via `bundle lock --add-platform x86_64-linux` (or what `ruby -v` reports). There is a pending issue in Rubygems resulting in picking up the wrong platform, `x86_64-linux-musl` in your case.

Extending on @tisba  's suggestion

```
gem uninstall libv8-node
# uninstall all
bundle lock --add-platform x86_64-linux
bundle update libv8-node
```

**Comment by tisba** [comment]
@rellampec that's what is in https://github.com/rubyjs/mini_racer/?tab=readme-ov-file#supported-ruby-versions--troubleshooting. I'm wondering what I can do to make this more prominent.

**Comment by rellampec** [comment]
@tisba not much on the README file. But that's what issues are for, I guess. Sometimes they can complement the information that would otherwise get too condensed in the main page :)
