### ISSUE TITLE
libv8_monolith.a: No such file or directory - install / compile failure - ?

### ISSUE THREAD

**Issue by lejeczek** [rubyjs/mini_racer#243]
Hi.
A newcomer to it all so go easy on me if this is not a "real" bug.
From what I gathered 'mini_racer' pulls in something and looks for something else?

[root@33a49fd1b5e1 /]# gem install mini_racer
Successfully installed libv8-node-16.10.0.0-x86_64-linux-musl
Building native extensions. This could take a while...
ERROR:  Error installing mini_racer:
ERROR: Failed to build gem native extension.
    current directory: /usr/local/share/gems/gems/mini_racer-0.6.2/ext/mini_racer_extension
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20220302-86966-556hyk.rb extconf.rb
checking for -lpthread... yes
creating Makefile
current directory: /usr/local/share/gems/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR=" clean
rm -f 
rm -f mini_racer_extension.so  *.o  *.bak mkmf.log .*.time

current directory: /usr/local/share/gems/gems/mini_racer-0.6.2/ext/mini_racer_extension
make "DESTDIR="
g++ -I. -I/usr/local/share/gems/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -DENGINE_IS_CRUBY  -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -rdynamic -std=c++14 -fpermissive -fvisibility=hidden  -fms-extensions -m64 -o mini_racer_extension.o -c mini_racer_extension.cc
rm -f mini_racer_extension.so
g++ -shared -o mini_racer_extension.so mini_racer_extension.o -L. -L/usr/lib64 /usr/local/share/gems/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/x86_64-linux/libv8/obj/libv8_monolith.a  -lstdc++ -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -m64  -lruby -lpthread  -lm   -lc
g++: error: /usr/local/share/gems/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/x86_64-linux/libv8/obj/libv8_monolith.a: No such file or directory
make: *** [Makefile:262: mini_racer_extension.so] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/share/gems/gems/mini_racer-0.6.2 for inspection.
Results logged to /usr/local/lib64/gems/ruby/mini_racer-0.6.2/gem_make.out

An obvious question - how to rectify that?
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

many thanks, L.

**Comment by tisba** [comment]
hey @lejeczek, that's a known "problem", please check out https://github.com/rubyjs/mini_racer#troubleshooting.

**Comment by lejeczek** [comment]
Hi.
Thanks for the info. I thought I'd start here with the 'racer' but first original thing that made me worrying was:

[root@33a49fd1b5e1 discourse]# gem update --system
Updating rubygems-update
Successfully installed rubygems-update-3.3.8
Parsing documentation for rubygems-update-3.3.8
Done installing documentation for rubygems-update after 0 seconds
Parsing documentation for rubygems-update-3.3.8
Done installing documentation for rubygems-update after 0 seconds
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/share/gems/gems/rubygems-update-3.3.8

Doing:
[root@33a49fd1b5e1 discourse]# bundle config unset deployment 
[root@33a49fd1b5e1 discourse]# bundle lock --add-platform=x86_64-linux
Does not seem to have any positive effect, error persists.

I look an think this is weird:
...
-I/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/include
...
Why 'musl' ?

many thanks, L.

**Comment by tisba** [comment]
The error when you're updating Rubygems looks strange 🤔 

Can you check that you're indeed running on the latest Rubygems (`gem --version`) and bundler (`bundle --version`)?

**Comment by rkistner** [comment]
I'm getting the same error.

Rubygems 3.3.9
Bundler 2.3.9
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

**Comment by wesgarrison** [comment]
I had this issue and found updating rubygems, bundler, then `bundle lock --add-platform x86_64-linux` worked to prevent the `musl` version of the gem.

Ruby 3.1.1 for me.

**Comment by tisba** [comment]
I know this is annoying and frustrating, but the issue is upstream in Rubygems (see for example https://github.com/rubygems/rubygems/pull/4488).

@rkistner please make sure to follow https://github.com/rubyjs/mini_racer#troubleshooting. If this is not solving your problem, please create a new issue with steps to reproduce. All supported Ruby versions are known to work so far and I'd like to extend the troubleshooting guide if there is missing something.

**Comment by picman** [comment]
In my case there was a conflict between directory names: _x86_64-linux_  X _x86_64-linux-**gnu**_. After creating a corresponding link, the build passed:

``` shell
cd /var/lib/gems/3.2.0/gems/libv8-node-16.19.0.1-x86_64-linux/vendor/v8
sudo ln -s x86_64-linux x86_64-linux-gnu
```

**Comment by duleorlovic** [comment]
> In my case there was a conflict between directory names: _x86_64-linux_ X _x86_64-linux-**gnu**_. After creating a corresponding link, the build passed:
> 
> ```shell
> cd /var/lib/gems/3.2.0/gems/libv8-node-16.19.0.1-x86_64-linux/vendor/v8
> sudo ln -s x86_64-linux x86_64-linux-gnu
> ```

Thanks for solution, for me also creating a symlink solve the issue with those "hardcoded" paths
```
cd /home/ubuntu/xceednet/shared/bundle/ruby/2.7.0/gems/libv8-node-16.10.0.0-x86_64-linux-musl/vendor/v8/
ln -s x86_64-linux-musl x86_64-linux
```
