### ISSUE TITLE
The browser running result is different from the server running result

### ISSUE THREAD

**Issue by fanxy1** [rubyjs/mini_racer#248]
mini_racer 0.3.1
ruby 2.5.0
rails 5.2.0

browser perform is success，but rails server perform is different，how to debugger in rails server

**Comment by tisba** [comment]
Hey! I don't quite follow what your issue is, that you're experiencing. Can you elaborate? Especially what do you mean by "browser perform is success"?

Also, please update `mini_racer` to a more recent version. A lot of issues have been addressed since `0.3.1`. Your Ruby version is also quite outdated and unsupported.

**Comment by fanxy1** [comment]
> Hey! I don't quite follow what your issue is, that you're experiencing. Can you elaborate? Especially what do you mean by "browser perform is success"?
> 
> Also, please update `mini_racer` to a more recent version. A lot of issues have been addressed since `0.3.1`. Your Ruby version is also quite outdated and unsupported.

I want to debug in rails console, when rails console perform js code, What's the way to debug js?

**Comment by fanxy1** [comment]
Sorry, My english is poor, i wanna to binding.pry in js code, like binding.pry in ruby code.

```
def test
  binding.pry
end
```

```
function test(){
  binding.pry
}
```

perform them in rails console

**Comment by tisba** [comment]
No worries, I'm also not a native speaker :)

To your question:

I'm not aware of a feature like that in `mini_racer`. What I used to do sometimes is hooking up a `console.log` which just prints out the value and do some "debugging" like this.

**Comment by fanxy1** [comment]
> No worries, I'm also not a native speaker :)
> 
> To your question:
> 
> I'm not aware of a feature like that in `mini_racer`. What I used to do sometimes is hooking up a `console.log` which just prints out the value and do some "debugging" like this.

thinks, I try to use `console.log` to debug.
