### ISSUE TITLE
Can't deploy to heroku after updating mini_racer

### ISSUE THREAD

**Issue by toddmetheny** [rubyjs/mini_racer#249]
Recently got a mac with an M1 which prompted an upgrade to mini_racer 0.5.0 (previously on 0.3.0). The update allowed the app to work on my local machine but the build consistently fails when I attempt to push to heroku. None of the workarounds I've seen anywhere have done the trick.

**Comment by tisba** [comment]
Without any details, logs, error messages, it's pretty hard to help. Could you provide something more to look at?

**Comment by tisba** [comment]
Closing for now. If you can provide information what is not working, feel free to let us know.
