### ISSUE TITLE
Context has no Isolate available anymore

### ISSUE THREAD

**Issue by mathieujobin** [rubyjs/mini_racer#269]
I am upgrading a project that was using V8::Context#load directly with therubyracer.
I am trying to replace it with MiniRacer::Context

getting this error

```
      MiniRacer::RuntimeError:
        Context has no Isolate available anymore
      # ./vendor/bundle/ruby/2.7.0/gems/mini_racer-0.6.3/lib/mini_racer.rb:225:in `isolate_mutex'
      # ./vendor/bundle/ruby/2.7.0/gems/mini_racer-0.6.3/lib/mini_racer.rb:225:in `eval'
      # ./lib/lib_dsl/value/custom_function.rb:27:in `block in <class:CustomFunction>'
```

with this code

```ruby
      set_callback :initialize, :after do
        @function_ref = js_context.eval("(#{body})")
      end
```

I'm not too sure what it means?
it crashes here

https://github.com/rubyjs/mini_racer/blob/719abdb1a4881d65831830e6e6fb5ca1bcedbc1e/lib/mini_racer.rb#L225

**Comment by tisba** [comment]
Hey @mathieujobin. Could you provide a bit more context? Ideally something that is reproducible. With just this three lines of code you provided, it's difficult to help.

**Comment by mathieujobin** [comment]
Looks like I found the solution to my last problem... reading #224 I realize I now need to make the call to the context, but my functions don't have names as shown... so I am creating anonymous names... such like this.

```ruby
      set_callback :initialize, :after do
        @fn_name = "custom_#{SecureRandom.hex(5)}"
        @function_ref = js_context.eval("#{@fn_name} = (#{body})")
      end
```
then I am able to make calls like this

```ruby
      def call(environment, args)
        initialize_js_context(environment)
        js_context.call(@fn_name, *args)
      end
```

very happy ! Thank you
