### ISSUE TITLE
bundler install error

### ISSUE THREAD

**Issue by OUCyf** [rubyjs/mini_racer#270]
Greeting,
This is Fu. I got an error when I wanted to install this project using M1-max chip. I failed to install mini_racer, and I have check many approaches but it always failed. My configurations are: 
- gcc-12 (or clang arm64-apple-darwin22.2.0)
- Bundler version 2.4.2
- gem version 3.4.2

Error is:
```
...
/Users/yinfu/gems/gems/bundler-2.4.2/lib/bundler/worker.rb:90:in `block (2
levels) in create_threads'

An error occurred while installing mini_racer (0.6.3), and Bundler
cannot continue.

In Gemfile:
  mini_racer
```

Best,
Fu

**Comment by tisba** [comment]
Hey Fu. Can you post more of the error message? Also, if you installed via `bundle install`, can you post your `Gemfile` and `Gemfile.lock`? Does `gem install mini_racer` work?

Last but not least, check out the troubleshooting section in the README: https://github.com/rubyjs/mini_racer#troubleshooting.

**Comment by elliot** [comment]
Try running this to add `arm64-darwin` to your lockfile and reinstall

```shell
gem update --system
gem uninstall --all mini_racer libv8-node
bundle lock --add-platform arm64-darwin
bundle install
```

**Comment by kenkyusha** [comment]
Having same problem with MacBook Pro 2019 (intel chip), I am guessing this fix by @elliot does not work for that?

**Comment by tisba** [comment]
@kenkyusha it does, but you'd need to provide the correct platform of course. Please check https://github.com/rubyjs/mini_racer/#troubleshooting if you're having installation issues.

**Comment by davidrakoto** [comment]
> Try running this to add `arm64-darwin` to your lockfile and reinstall
> 
> ```shell
> gem update --system
> gem uninstall --all mini_racer libv8-node
> bundle lock --add-platform arm64-darwin
> bundle install
> ```

I had this issue for two weeks and this solved it, thanks a lot
