### ISSUE TITLE
Update default branch to `main`

### ISSUE THREAD

**Issue by seanmakesgames** [rubyjs/mini_racer#273]
Update to the current github standard.

**Comment by lloeki** [comment]
Related to https://github.com/rubyjs/libv8-node/issues/47

**Comment by tisba** [comment]
Looks like @SamSaffron already did the work 🥳 

Since I had to look it up, here is how I changed the default branch locally:

```
git fetch
git checkout main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
git branch -d master
```

**Comment by seanmakesgames** [comment]
yay! looks great. :D
