### ISSUE TITLE
failed to build libv8 16.19.0... is jruby supported?

### ISSUE THREAD

**Issue by AFlowOfCode** [rubyjs/mini_racer#313]
`$ hostnamectl`
```
Operating System: Amazon Linux 2
Kernel: Linux 5.10.217-205.860.amzn2.x86_64
Architecture: x86-64
```

Hello, I've tried to install `mini_racer` & each time it fails in a way that doesn't seem clear (after 20 - 30 minutes of attempted installation). I get this line `Libv8::Node::BuilderError: failed to build libv8 16.19.0`, and the issue in general seems very similar to https://github.com/rubyjs/mini_racer/issues/252, except that I'm not using any form of windows.

Assuming it's not the Amazon Linux platform, the main thing that comes to mind is that it's failing because the rails app I'm trying to use with it is using jruby, specifically `jruby-9.3.9.0`. I couldn't find any information whether or not `mini_racer` works with jruby. Could someone confirm that it is or isn't supported?

I'm having trouble finding an ES6-supported js runtime that works with jruby. As far as I can tell, none at least say they do. The app's currently using `therubyrhino` but that explicitly doesn't support ES6. I'd love to use this runtime if possible as I've had good experiences with it on other non-jruby projects. 

If it's indeed jruby that's the problem, does anyone happen to know of an ES6-capable js runtime that's compatible with jruby? I must say I'll be rather disappointed if there simply aren't any. But that'd be my problem.

Thank you for your time and any assistance!

**Comment by SamSaffron** [comment]
We have support for truffle ruby but not jruby
